# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

author: Jing Roy Yang
author_other: 杨靖
title: Jing Roy Yang
email: roy.j.yang@qut.edu.au
motto: >
  <a href="https://en.wikipedia.org/wiki/Fan_Zhongyan#Literary_works"
  target="_blank">“不以物喜，不以己悲”（<宋>范仲淹 1046）</a>
description: > # this means to ignore newlines until "url:"
  Welcome to my personal webpage
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>.
  Based on <a href="https://github.com/alshedivat/al-folio">al-folio</a>.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

# set to true if you want to display last updated in the footer
last_updated: true

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: roy-jingyang # your GitHub user name
linkedin_username: roy-jingyang
scholar_userid: #Ms1FNhsAAAAJ # your Google Scholar ID
orcid_id: 0000-0001-9218-6954 # your ORCID ID
research_gate_profile: # your profile on ResearchGate

cv_filename: YANG_CV.pdf

contact_note: >

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

# your blog must have a name for it to show up in the nav bar
blog_name:
blog_description:
permalink: #/blog/:year/:title/

# Pagination
pagination:
  enabled: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 3

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - LICENSE
  - .gitignore
  - setup.md
keep_files:
  - CNAME


# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-paginate-v2
  - jekyll/scholar
  - jemoji
  - jekyll-seo-tag

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  last_name: Yang
  first_name: [Jing, J., Roy, R., J.R.]

  style: apa
  locale: en

  sort_by: year, month
  order: descending

  source: /_bibliography/
  bibliography: publications.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Jekyll Sass options
# -----------------------------------------------------------------------------
sass_dir: _sass

# -----------------------------------------------------------------------------
# Styling and JS dependencies
# -----------------------------------------------------------------------------
bootstrap:
  link: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"

bootstrapJS:
  link: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"

jquery:
  link: "https://code.jquery.com/jquery-3.7.1.js"
